# Generated by Django 5.1.6 on 2025-03-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_brand_remove_cartitem_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='seller',
            new_name='owner',
        ),
    ]
