# Generated by Django 5.1.6 on 2025-03-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_seller_cartitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
    ]
