# Generated by Django 5.1.6 on 2025-03-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
