# Generated by Django 5.1.6 on 2025-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
    ]
