# Generated by Django 5.1.6 on 2025-03-30 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('description', models.TextField(verbose_name='Description')),
                ('size', models.CharField(choices=[('x', 'X'), ('xl', 'XL'), ('xxl', 'XXL'), ('3xl', '3XL')], max_length=50, verbose_name='Size')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Discount Percentage')),
                ('category', models.CharField(choices=[('Man Fashion', [('Man Shirt', 'Man T-Shirt'), ('Man Shoes', 'Man Shoes'), ('Man Work Equipment', 'Man Work Equipment'), ('Man Pant', 'Man Pants'), ('Man Underwear', 'Man Underwear')]), ("Women's fashion", [('Dress', 'Dress'), ('Woman T-Shirt', 'Woman T-shirt'), ('Woman Pants', 'Woman Pants'), ('Skirts', 'skirts'), ('Bags', 'Bags'), ('High Heels', 'High Heels'), ('Bikini', 'Bikini')])], max_length=50, verbose_name='Category')),
                ('image', models.FileField(null=True, upload_to='items_images', verbose_name='Image')),
                ('slug', models.SlugField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
        ),
    ]
