# Generated by Django 5.1.6 on 2025-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Man Fashion', [('man_tshirt', 'Man T-Shirt'), ('man_shoes', 'Man Shoes'), ('manwork_equipment', 'Man Work Equipment'), ('man_pants', 'Man Pants'), ('man_underwear', 'Man Underwear')]), ("Women's fashion", [('dress', 'Dress'), ('woman_tshirt', 'Woman T-shirt'), ('woman_pants', 'Woman Pants'), ('skirts', 'skirts'), ('bags', 'Bags'), ('high_heels', 'High Heels'), ('bikini', 'Bikini')])], max_length=50, verbose_name='Category'),
        ),
    ]
