# Generated by Django 5.1.6 on 2025-03-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', "Men's Wear"), ('women', "Women's Wear"), ('footwears', 'Footwears'), ('bags', 'Bags')], max_length=10, null=True, verbose_name='Category'),
        ),
    ]
