# Generated by Django 5.1.6 on 2025-03-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Man Fashion', [('Man Shirt', 'Man T-Shirt'), ('Man Shoes', 'Man Shoes'), ('Man Work Equipment', 'Man Work Equipment'), ('Man Pant', 'Man Pants'), ('Man Underwear', 'Man Underwear')]), ("Women's fashion", [('Dress', 'Dress'), ('Woman T-Shirt', 'Woman T-shirt'), ('Woman Pants', 'Woman Pants'), ('Skirts', 'skirts'), ('Bags', 'Bags'), ('High Heels', 'High Heels'), ('Bikini', 'Bikini')])], max_length=50, null=True, verbose_name='Category'),
        ),
    ]
