# Generated by Django 5.1.6 on 2025-03-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('x', 'X'), ('xl', 'XL'), ('xxl', 'XXL'), ('3xl', '3XL')], max_length=50, null=True, verbose_name='Size'),
        ),
    ]
