# Generated by Django 5.1.6 on 2025-03-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
